docs: Improve Run a node - Overview
oasisprotocol/docs pull request #112
Opened 2022-05-31 08:29 UTC by amela

Preview:

2022-06-03 11:47 UTC, matevz requested changes
The content of this document is beginning to overlap with https://docs.oasis.dev/general/contribute-to-the-network/run-validator

I'm not sure how I would reorganize the docs for this yet.

2022-06-03 11:47 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +organisation in participating in the Oasis network as a node operator. To join
We use US English.

```suggestion
organization in participating in the Oasis network as a node operator. To join 
```

2022-06-03 11:47 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +the network we recommend you first try running nodes on the Testnet. The
```suggestion
the network we recommend you first try running a node on the Testnet. The 
```

2022-06-03 11:47 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +Testnet is a playground, where you can learn and experiment without the risk
```suggestion
Testnet is a playground where you can learn and experiment without the risk 
```

2022-06-03 11:47 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +of loosing real tokens.
```suggestion
of losing real tokens. 
```

2022-06-03 11:47 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +
Here, I would mention the third option - client nodes. Add links where appropriate.

```suggestion

If you are building a service on top of the Oasis network, we suggest
that you set up a **non-validator node** and (optionally) a **ParaTime client
node**, so your service do not depend on third party endpoints which are
often behind a traffic limiter.
```

2022-06-08 08:39 UTC, matevz approved these changes
Some minor nits, otherwise looks good!

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +[Trusted Execution Environment (TEE)]: ./prerequisites/set-up-trusted-execution-environment-tee.md
```suggestion
[Trusted Execution Environment (TEE)]:
  ./prerequisites/set-up-trusted-execution-environment-tee.md
```

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +If you are building a service on top of the Oasis Network, we suggest
```suggestion
Finally, if you are building a service on top of the Oasis Network, we suggest
```

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +that you set up a [non-validator node] and (optionally) a [ParaTime client
```suggestion
that you set up your own **[Non-validator node]** and (optionally) a **[ParaTime client
```

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +[non-validator node]: ./set-up-your-node/run-non-validator.md
```suggestion
[Non-validator node]: ./set-up-your-node/run-non-validator.md
```

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +node], so your service do not depend on third party endpoints which are
```suggestion
node]**, so that your service do not depend on any third party endpoints which are
```

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +To run a **ParaTime node** make sure to first set up a Validator node. Then set
```suggestion
To run a **ParaTime node** make sure to first set up a Validator node. Then, set 
```

2022-06-08 08:39 UTC, matevz commented on docs/general/run-a-node/node-operator-overview.mdx
> +up a [Trusted Execution Environment (TEE)]. After that proceed to the [Run a
```suggestion
up a [Trusted Execution Environment (TEE)], if you want to run confidential ParaTimes. After that, proceed to the [Run a 
```

2022-06-09 08:31 UTC, amela commented on docs/general/run-a-node/node-operator-overview.mdx
> +[Trusted Execution Environment (TEE)]: ./prerequisites/set-up-trusted-execution-environment-tee.md
If I apply this change link does not work, so I kept the old version.

2022-06-09 08:56 UTC, merged