docs: Move and update Stake Requirements
oasisprotocol/docs pull request #115
Opened 2022-06-03 08:53 UTC by amela

- [ ] Move Stake Requirements to run-a-node/prerequisites/
- [ ] Add info about the Testnet Faucet
- [ ] Delete contribute-to-the-network/run-validator.md
- [ ] Check links

Preview:

2022-06-08 07:51 UTC, matevz commented
This seems like a duplicate of https://docs.oasis.dev/general/manage-tokens/advanced/oasis-cli-tools/common-staking-info?

2022-06-08 08:31 UTC, matevz requested changes

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +[current entity's staking threshold]: ../../oasis-network/genesis-doc.md#node-and-paratime-token-thresholds
```suggestion
[staking thresholds]: ../../oasis-network/genesis-doc.md#staking-thresholds
```

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +[current validator node's staking threshold].
```suggestion
[current validator node's staking threshold][staking thresholds].
```

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +staking threshold].
```suggestion
staking threshold][staking thresholds].
```

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +[current validator node's staking threshold]: ../../oasis-network/genesis-doc.md#node-and-paratime-token-thresholds
Unify with the link above.

```suggestion
```

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +
```suggestion
Staking thresholds may change in the future. Read [Common staking info] chapter,
to learn how to check the current network thresholds directly from the `oasis-node`.

[Common staking info]: ../../manage-tokens/advanced/oasis-cli-tools/common-staking-info.md

```

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +For the Testnet you are going to need TEST tokens. To receive TEST tokens please
```suggestion
For the Testnet you are going to need TEST tokens. You can receive a limited number of
TEST by using our [Oasis Network Testnet Faucet]. For more tokens please contact us at
our official [Discord #testnet channel][discord-testnet].

[discord-testnet]: https://discord.com/channels/748635004384313474/960599828662976522
```

2022-06-08 08:31 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +use the [Oasis Network Testnet Faucet].
```suggestion
```

2022-06-13 12:41 UTC, amela commented
Yes it is similar to the https://docs.oasis.dev/general/manage-tokens/advanced/oasis-cli-tools/common-staking-info. However `Stake Requirements` is meant to be read before setting up a node and to get the feel of how many tokens someone needs to be a validator.

2022-06-13 16:01 UTC, matevz approved these changes
Just one detail. Otherwise looks good. :+1:

2022-06-13 16:01 UTC, matevz commented on docs/general/run-a-node/prerequisites/stake-requirements.md
> +For more information about obtaining information on your entity's account, see
I would remove the admonition and move this as a normal paragraph just before line 25 (`Staking thresholds may change in the future...`).

2022-06-13 19:43 UTC, merged