Start security section for Sapphire/OPL
oasisprotocol/docs pull request #513
Opened 2023-08-29 22:02 UTC by aefhm

2023-08-29 22:02 UTC, kostko commented
Task linked: [CU-8692kbhwx Storage I/O Patterns](https://app.clickup.com/t/8692kbhwx)

2023-09-05 10:02 UTC, matevz requested changes
First pass.

2023-09-05 10:02 UTC, matevz commented on docs/dapp/sapphire/security.md
> +description: Security recommendations for Sapphire
Perhaps something more fancy? Security guide? Security handbook? Security cookbook? ;)

2023-09-05 10:02 UTC, matevz commented on docs/dapp/sapphire/security.md
> +
This is similar to what we mention in https://github.com/oasisprotocol/docs/blob/main/docs/dapp/sapphire/guide.mdx#L188

Can you check the vocabulary so it's synced. Also, we can add a link pointing to this Security chapter (e.g. to learn more about Storage I/O patterns and how to mitigate them, read our [Security handbook for Sapphire](./security.md#storage-i-o-patterns).

2023-09-05 10:02 UTC, matevz commented on docs/dapp/sapphire/security.md
> +You can also trace a particular transaction.
This is for local tests, right? So the TransactionHash is always the same? If so, then:

```suggestion
You can also trace a particular transaction, once you know its hash.
```

2023-09-05 10:02 UTC, matevz commented on docs/dapp/sapphire/security.md
> +recommended. E.g. 64 byte value will still be distinct from a 128 byte value.
```suggestion
recommended. E.g. 64-byte value will still be distinct from a 128-byte value.
```

2023-09-05 10:02 UTC, matevz commented on sidebarDapp.js
> +        'dapp/sapphire/security',
`addresses` and `precompiles` are a kind of "reference guides" and I would leave them at the bottom. Could you put `security` after the `browser` chapter?

2023-09-05 10:02 UTC, matevz commented on docs/dapp/sapphire/security.md
> +Work in Progress
I would mention "storage I/O pattern" and "gas usage pattern" here. Maybe some other pattern?

2023-09-05 21:08 UTC, aefhm commented on docs/dapp/sapphire/security.md
> +You can also trace a particular transaction.
> This is for local tests, right?

Yes, but you can also do access mainnet archival node if you wanted to.

```sh
npx hardhat trace --hash 0xTransactionHash --rpc https://url # must be archive node
```

2023-09-05 21:31 UTC, aefhm commented on docs/dapp/sapphire/security.md
> +description: Security recommendations for Sapphire
😆 alright alright. How about these?

A.
```suggestion
description: Savory Security: A Recipe for Protection
```

B.
```suggestion
description: Secure dApps: Recipes for Confidentiality
```

C.
```suggestion
description: Smart contract confidentiality cookbook
```

2023-09-26 16:18 UTC, aefhm commented on docs/dapp/sapphire/security.md
> +
Makes sense. Added a link.

2023-11-13 11:40 UTC, matevz approved these changes
Some minor nits. Otherwise, LGTM!

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/guide.mdx
> +[chapter]: ./security.md#storage-access-patterns
```suggestion
so you may need to obfuscate that, too. See [Security chapter] for more
recommendations.

[Security chapter]: ./security.md#storage-access-patterns
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +}
Maybe adding ellipsis so that it's clear the two requires are only at the very beginning for authorization and not the sole purpose of the `transferFrom` function.

```suggestion
  // ...
}
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +}
```suggestion
  // ...
}
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +[precompile]: https://github.com/oasisprotocol/sapphire-paratime/blob/08b5fa24783ea576207dacde20ff4d20a1c7dded/contracts/contracts/Sapphire.sol#L28-L29
Let's use the new fancy Sapphire.sol API reference ;)

```suggestion
[precompile]: https://api.docs.oasis.io/sol/sapphire-contracts/contracts/Sapphire.sol/library.Sapphire.html#padgas
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +[used]: https://github.com/oasisprotocol/sapphire-paratime/blob/08b5fa24783ea576207dacde20ff4d20a1c7dded/contracts/contracts/Sapphire.sol#L26-L27
```suggestion
[used]: https://api.docs.oasis.io/sol/sapphire-contracts/contracts/Sapphire.sol/library.Sapphire.html#gasused
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +description: Security recommendations for Sapphire
I vote for B. ;)

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +non-unique data size. E.g. 64-byte value will still be distinct from a
Let's use more bolds in the chapter.

```suggestion
For both [gas] usage and confidentiality purposes, we **recommend using
non-unique data size**. E.g. 64-byte value will still be distinct from a
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +taken, but sometimes the balance of a user as well (in the case of a diligent
```suggestion
taken, **but sometimes the balance of a user as well** (in the case of a diligent
```

2023-11-13 11:40 UTC, matevz commented on docs/dapp/sapphire/security.md
> +in a transaction.
```suggestion
provides a [precompile] for dApp developers to **pad the amount of gas used
in a transaction**.
```

2023-11-14 17:21 UTC, merged