set-up-your-node, oasis-cli-tools: Update staking thresholds and tooling for Damask
oasisprotocol/docs pull request #77
Opened 2022-04-13 13:43 UTC by matevz

Merge after https://github.com/oasisprotocol/docs/pull/79

2022-04-13 19:07 UTC, kostko requested changes, later dismissed

2022-04-13 19:07 UTC, kostko commented on docs/general/run-a-node/set-up-your-node/run-a-paratime-node.mdx
> +* Compute node staking threshold (currently 50,000 tokens),
This is incorrect, the previous value was correct. 50k is for registering a runtime.

2022-04-20 10:05 UTC, ptrus commented on docs/general/manage-tokens/advanced/oasis-cli-tools/common-staking-info.md
> +almost 8 billion tokens are in the **common pool**.
In the updated example, there are fewer tokens in the common pool.

2022-04-20 10:09 UTC, matevz commented on docs/general/manage-tokens/advanced/oasis-cli-tools/common-staking-info.md
> +almost 8 billion tokens are in the **common pool**.
Thanks, missed those.

2022-05-11 07:37 UTC, ptrus approved these changes

2022-05-12 08:07 UTC, merged