run-archive-node: add docs on how to run an archive node
oasisprotocol/docs pull request #81
Opened 2022-04-18 07:04 UTC by ptrus

TODO:
- add a note that archive node is currently only supported in `21.x`

2022-04-20 12:44 UTC, kostko commented on docs/general/run-a-node/set-up-your-node/run-archive-node.md
> +To ensure node is running in archive node, run the following command:
```suggestion
To ensure the node is running in archive mode, run the following command:
```

2022-05-10 10:48 UTC, matevz requested changes
Can you also limit the line length to 80 characters.

2022-05-10 10:48 UTC, matevz commented on docs/general/run-a-node/set-up-your-node/run-archive-node.md
> +  // other fields emitted ...
```suggestion
  // other fields omitted ...
```

2022-05-10 10:48 UTC, matevz commented on docs/general/run-a-node/set-up-your-node/run-archive-node.md
> +
```suggestion
```

2022-05-10 10:48 UTC, matevz commented on docs/general/run-a-node/set-up-your-node/run-archive-node.md
> +
```suggestion
```

2022-07-15 16:26 UTC, matevz approved these changes
Just a small nit, otherwise ok.

2022-07-15 16:26 UTC, matevz commented on docs/general/run-a-node/set-up-your-node/run-archive-node.md
> +oasis-node control status --address /node/data/internal.sock
```suggestion
oasis-node control status -a unix:/node/data/internal.sock
```

2022-07-19 06:42 UTC, merged